/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cheque.java
 *
 * Created on 20-Sep-2009, 11:24:01
 */

package proffittcenter;

import java.util.prefs.Preferences;
import javax.swing.JRootPane;

/**
 *
 * @author HP_Owner
 */
public class Cheque extends EscapeDialog {

    Preferences root = Preferences.userNodeForPackage(getClass());
    int amount;
    /** Creates new form Cheque */
    public Cheque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JRootPane rp = getRootPane();
        rp.setDefaultButton(okBtn);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chequeText = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("proffittcenterworkingcopy/resource/Cheque"); // NOI18N
        setTitle(bundle.getString("title")); // NOI18N
        setName("Cheque"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("proffittcenter/resource/Cheque"); // NOI18N
        jLabel1.setText(bundle1.getString("Coupon.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        chequeText.setText(bundle1.getString("Cheque.chequeText.text")); // NOI18N
        chequeText.setName("chequeText"); // NOI18N
        chequeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                chequeTextFocusLost(evt);
            }
        });
        chequeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chequeTextKeyReleased(evt);
            }
        });

        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenterworkingcopy/resource/OK.png"))); // NOI18N
        okBtn.setContentAreaFilled(false);
        okBtn.setName("okBtn"); // NOI18N
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chequeText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chequeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chequeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chequeTextFocusLost
        String s=StringOps.numericOnly(chequeText.getText());
        if(s.isEmpty()){
            chequeText.requestFocus();
            return;
        }
        amount=Integer.parseInt(s);
        chequeText.setText((new Money(amount)).toString());
        amount=0;
}//GEN-LAST:event_chequeTextFocusLost

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        String s=StringOps.numericOnly(chequeText.getText());
        if(s.isEmpty()){
            chequeText.requestFocus();
            return;
        }
        amount=Integer.parseInt(s);
        setVisible(false);
}//GEN-LAST:event_okBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        amount=0;
    }//GEN-LAST:event_formWindowClosing

    private void chequeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chequeTextKeyReleased
        Money.asMoney(chequeText);
    }//GEN-LAST:event_chequeTextKeyReleased

    public  int execute(int owing){
        amount=owing;
        chequeText.setText((new Money(amount)).toString());
        amount=0;
//        //FormRestore.createPosition(this, root);
        Audio.play("TaDa");
        setVisible(true);
//        //FormRestore.destroyPosition(this, root);
        return amount;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cheque dialog = new Cheque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chequeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables

}
