/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Customer.java
 *
 * Created on 26-Jul-2009, 18:02:42
 */
package proffittcenter;

import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ResourceBundle;
import java.util.prefs.Preferences;
import javax.swing.JRootPane;

/**
 *
 * @author HP_Owner
 */
public class Customer extends EscapeDialog {

    Preferences root = Preferences.userNodeForPackage(getClass());
    ResourceBundle bundle = ResourceBundle.getBundle("proffittcenterworkingcopy/resource/Customer");
    private boolean isNew = false;
    private boolean printrequired = false;
    private Long customer = 0l;
    private Integer creditLimit;
    private Integer discount;
    private boolean ownUse;

    /** Creates new form Customer */
    public Customer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JRootPane rp = getRootPane();
        rp.setDefaultButton(okButton);
        Main.mainHelpBroker.enableHelpKey(getRootPane(), "Customer", Main.mainHelpSet);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSurname = new javax.swing.JTextField();
        jForename = new javax.swing.JTextField();
        jAlternative = new javax.swing.JTextField();
        jNumber = new javax.swing.JTextField();
        jRoad = new javax.swing.JTextField();
        jSpare = new javax.swing.JTextField();
        jTown = new javax.swing.JTextField();
        jCounty = new javax.swing.JTextField();
        jPostcode = new javax.swing.JTextField();
        jTel1 = new javax.swing.JTextField();
        jTel2 = new javax.swing.JTextField();
        jCode = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jAccount = new javax.swing.JTextField();
        discountSpinner = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        creditLimitSpinner = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("proffittcenterworkingcopy/resource/Customer"); // NOI18N
        setTitle(bundle.getString("Customer.title")); // NOI18N
        setName("Customer"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText(bundle.getString("Customer.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText(bundle.getString("Customer.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText(bundle.getString("Customer.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText(bundle.getString("Customer.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText(bundle.getString("Customer.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText(bundle.getString("Customer.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText(bundle.getString("Customer.jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText(bundle.getString("Customer.jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText(bundle.getString("Customer.jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText(bundle.getString("Customer.jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText(bundle.getString("Customer.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText(bundle.getString("Customer.jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jSurname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSurname.setName("jSurname"); // NOI18N
        jSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSurnameFocusLost(evt);
            }
        });

        jForename.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jForename.setName("jForename"); // NOI18N
        jForename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jForenameFocusLost(evt);
            }
        });

        jAlternative.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAlternative.setName("jAlternative"); // NOI18N
        jAlternative.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAlternativeFocusLost(evt);
            }
        });

        jNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNumber.setName("jNumber"); // NOI18N
        jNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNumberFocusLost(evt);
            }
        });

        jRoad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRoad.setName("jRoad"); // NOI18N
        jRoad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRoadFocusLost(evt);
            }
        });

        jSpare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSpare.setName("jSpare"); // NOI18N
        jSpare.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpareFocusLost(evt);
            }
        });

        jTown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTown.setName("jTown"); // NOI18N
        jTown.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTownFocusLost(evt);
            }
        });

        jCounty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCounty.setName("jCounty"); // NOI18N
        jCounty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCountyFocusLost(evt);
            }
        });

        jPostcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPostcode.setName("jPostcode"); // NOI18N
        jPostcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPostcodeFocusLost(evt);
            }
        });

        jTel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTel1.setName("jTel1"); // NOI18N

        jTel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTel2.setName("jTel2"); // NOI18N

        jCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCode.setText(bundle.getString("Customer.jCode.text")); // NOI18N
        jCode.setName("jCode"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText(bundle.getString("Customer.jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAccount.setName("jAccount"); // NOI18N

        discountSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        discountSpinner.setName("discountSpinner"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText(bundle.getString("Customer.jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText(bundle.getString("Customer.jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenterworkingcopy/resource/Close24.png"))); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenterworkingcopy/resource/OK.png"))); // NOI18N
        okButton.setContentAreaFilled(false);
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenterworkingcopy/resource/Barcode.png"))); // NOI18N
        printButton.setContentAreaFilled(false);
        printButton.setName("printButton"); // NOI18N
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {closeButton, okButton});

        jLabel12.setText(bundle.getString("Customer.jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        creditLimitSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100000, 10));
        creditLimitSpinner.setName("creditLimitSpinner"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText(bundle.getString("Customer.jLabel17.text")+" ("+Main.shop.poundSymbol+"):"); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jForename, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jAlternative, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jRoad, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jSpare, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jTown, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jCounty, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jPostcode, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jTel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jTel2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(discountSpinner)
                                            .addComponent(creditLimitSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                        .addGap(206, 206, 206)
                                        .addComponent(jLabel12)))
                                .addGap(52, 52, 52))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCode, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jForename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jAlternative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditLimitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {discountSpinner, jLabel14});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCheckBox1, jLabel15});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
}//GEN-LAST:event_closeButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // save the data
        //first check all filled in
        if (jSurname.getText().isEmpty()) {
            jSurname.requestFocus();
            Audio.play("Ring");
            return;
        } else if (jNumber.getText().isEmpty()) {
            jNumber.requestFocus();
            Audio.play("Ring");
            return;
        } else if (jNumber.getText().isEmpty()) {
            jNumber.requestFocus();
            Audio.play("Ring");
            return;
        } else if (jRoad.getText().isEmpty()) {
            jRoad.requestFocus();
            return;
        } else if (jTown.getText().isEmpty()) {
            jTown.requestFocus();
            Audio.play("Ring");
            return;
        } else if (jCounty.getText().isEmpty()) {
            jCounty.requestFocus();
            Audio.play("Ring");
            return;
        }
        if (jPostcode.getText().isEmpty()) {
            jPostcode.requestFocus();
            Audio.play("Ring");
            return;
        } else if (jTel1.getText().isEmpty()) {
            jTel1.requestFocus();
            Audio.play("Ring");
            return;
        }
        //save the data
        if(!saveData()){
            jSurname.requestFocus();
            Audio.play("Ring");
            return;
        }
        //if print required then print
        if (printrequired) {
            BarcodePrinter.print(customer, jForename.getText()+jSurname.getText());
        }
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        if (isNew) {//need to delay print until saved
            printButton.setVisible(false);
            printrequired = true;
        } else {//print now
            String s = jForename.getText();
            BarcodePrinter.print(customer, jForename.getText() +" "+ jSurname.getText());
        }
    }//GEN-LAST:event_printButtonActionPerformed

    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formWindowClosed

    private void jSurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSurnameFocusLost
        jSurname.setText(StringOps.firstCaps(jSurname.getText()));
    }//GEN-LAST:event_jSurnameFocusLost

    private void jForenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jForenameFocusLost
        jForename.setText(StringOps.firstCaps(jForename.getText()));
    }//GEN-LAST:event_jForenameFocusLost

    private void jAlternativeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAlternativeFocusLost
        jAlternative.setText(StringOps.firstCaps(jAlternative.getText()));
    }//GEN-LAST:event_jAlternativeFocusLost

    private void jNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNumberFocusLost
        jNumber.setText(StringOps.firstCaps(jNumber.getText()));
    }//GEN-LAST:event_jNumberFocusLost

    private void jRoadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRoadFocusLost
        jRoad.setText(StringOps.firstCaps(jRoad.getText()));
    }//GEN-LAST:event_jRoadFocusLost

    private void jSpareFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpareFocusLost
        jSpare.setText(StringOps.firstCaps(jSpare.getText()));
    }//GEN-LAST:event_jSpareFocusLost

    private void jTownFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTownFocusLost
        jTown.setText(StringOps.firstCaps(jTown.getText()));
    }//GEN-LAST:event_jTownFocusLost

    private void jCountyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCountyFocusLost
        jCounty.setText(StringOps.firstCaps(jCounty.getText()));
    }//GEN-LAST:event_jCountyFocusLost

    private void jPostcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPostcodeFocusLost
        jPostcode.setText(jPostcode.getText().toUpperCase());
    }//GEN-LAST:event_jPostcodeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Customer dialog = new Customer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    boolean execute(Long customer,boolean ownUse) {
        this.customer = customer;
        this.ownUse=ownUse;
        Audio.play("Tada");
        //FormRestore.createPosition(this, root);
        printrequired = false;
        printButton.setVisible(true);
        if (customer == -1l) {
            //new customer required
            isNew = true;
            jCode.setText(" ");
            jSurname.setText(null);
            jForename.setText("");
            jAlternative.setText("");
            jNumber.setText("");
            jRoad.setText("");
            jSpare.setText("");
            jTown.setText("");
            jCounty.setText("");
            jPostcode.setText("");
            jTel1.setText("");
            jTel2.setText("");
            if(ownUse){
                jAccount.setText("Own use");
            } else {
                jAccount.setText("");
            }
            discountSpinner.getModel().setValue((Integer) 0);
            creditLimitSpinner.getModel().setValue((Integer) 0);
            creditLimit=0;
            discount = 0;
            jLabel17.setText(jLabel17.getText());
            jCheckBox1.setSelected(false);
        } else {
            isNew = false;
            //see if there is an existing customer in database
            //now need to check till/product table
            checkCustomer();
            creditLimit = (Integer) creditLimitSpinner.getValue();
            discount = (Integer) discountSpinner.getValue();
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        jSurname.requestFocus();
        setVisible(true);
        //FormRestore.destroyPosition(this, root);
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JSpinner creditLimitSpinner;
    private javax.swing.JSpinner discountSpinner;
    private javax.swing.JTextField jAccount;
    private javax.swing.JTextField jAlternative;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jCode;
    private javax.swing.JTextField jCounty;
    private javax.swing.JTextField jForename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPostcode;
    private javax.swing.JTextField jRoad;
    private javax.swing.JTextField jSpare;
    private javax.swing.JTextField jSurname;
    private javax.swing.JTextField jTel1;
    private javax.swing.JTextField jTel2;
    private javax.swing.JTextField jTown;
    private javax.swing.JButton okButton;
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables

    private boolean saveData() {
        try {            
            if(Main.operator.isChangeCreditLimits()||Main.operator.isOwner()){
                creditLimit = (Integer) creditLimitSpinner.getValue();
                discount = (Integer) discountSpinner.getValue();
            }
            if (isNew) {
                PreparedStatement np = Main.getConnection().prepareStatement(
                        "INSERT INTO " +
                        " Customers " +
                        " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                np.setNull(1, Types.BIGINT);//ID
                np.setNull(2, Types.DATE);//timestamp
                np.setString(3, jSurname.getText());
                np.setString(4, jPostcode.getText());
                np.setString(5, jRoad.getText());
                np.setString(6, jNumber.getText());
                np.setString(7, jSpare.getText());
                np.setString(8, jTown.getText());
                np.setString(9, jCounty.getText());
                np.setString(10, jTel1.getText());
                np.setString(11, jTel2.getText());
                np.setString(12, jForename.getText());
                np.setString(13, jAlternative.getText());
                np.setString(14, jAccount.getText());
                np.setInt(15, discount);
                np.setBoolean(16, jCheckBox1.isSelected());//stop
                np.setInt(17, creditLimit);
                np.executeUpdate();
                PreparedStatement np1 = Main.getConnection().prepareStatement(
                        "SELECT LAST_INSERT_ID() FROM Customers");
                ResultSet rs = np1.executeQuery();
                if (rs.first()) {
                    customer = rs.getLong(1);
                    rs.close();
                } else {
                    return false;
                }
                np.close();
            } else {//need to update
                PreparedStatement np = Main.getConnection().prepareStatement(
                        "UPDATE Customers SET " +
                        "Name1=?,PostCode=?," +
                        "Address1=?,Address2=?," +
                        "Address3=?,Town=?," +
                        "County=?,Name3=?,Phone1=?," +
                        "Phone2=?,Name2=?," +
                        "Account=?," +
                        "Discount=?,Stop=?,CreditLimit=? " +
                        "WHERE ID=? ");
                np.setString(1, jSurname.getText());//Name1
                np.setString(2, jPostcode.getText());//PostCode
                np.setString(3, jRoad.getText());//Address1
                np.setString(4, jNumber.getText());//Address2
                np.setString(5, jSpare.getText());//Address3
                np.setString(6, jTown.getText());//Town
                np.setString(7, jCounty.getText());//County
                np.setString(8, jAlternative.getText());//Alternative
                np.setString(9, jTel1.getText());//Phone1
                np.setString(10, jTel2.getText());//Phone2
                np.setString(11, jForename.getText());//Name2
                np.setString(12, jAccount.getText());//Account
                np.setInt(13, discount);//Discount
                np.setBoolean(14, jCheckBox1.isSelected());//Stop
                np.setInt(15, creditLimit);
                np.setLong(16, customer);//ID
                np.executeUpdate();
                np.close();
            }
        } catch (SQLException ex) {
            Audio.play("Ring");
            ex.printStackTrace();
            return false;
        }
        return true;
    }

    private boolean checkCustomer() {
        try {
            //now need to check till/product table
            PreparedStatement customerLookup = Main.getConnection().prepareStatement(
                    "SELECT Customers.* " +
                    "FROM Customers " +
                    " WHERE Customers.ID=? ");
            customerLookup.setLong(1, customer);
            ResultSet rs = customerLookup.executeQuery();
            if (!rs.first()) {
                //no customer
                jCode.setText(" ");
                rs.close();
                return false;
            } else {
                jCode.setText(customer.toString());
                jSurname.setText(rs.getString("Name1"));
                jForename.setText(rs.getString("Name2"));
                jAlternative.setText(rs.getString("Name3"));
                jNumber.setText(rs.getString("Address2"));
                jRoad.setText(rs.getString("Address1"));
                jSpare.setText(rs.getString("Address3"));
                jTown.setText(rs.getString("Town"));
                jCounty.setText(rs.getString("County"));
                jPostcode.setText(rs.getString("PostCode"));
                jTel1.setText(rs.getString("Phone1"));
                jTel2.setText(rs.getString("Phone2"));
                jAccount.setText(rs.getString("Account"));
                discountSpinner.getModel().setValue((Integer) rs.getInt("Discount"));
                jCheckBox1.setSelected(rs.getBoolean("Stop"));
                creditLimitSpinner.getModel().setValue(rs.getInt("CreditLimit"));
                rs.close();
                return true;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return false;
    }

    int getCreditLimit(long customer) {
        //return the credit limit
        try {
            //now need to check till/product table
            PreparedStatement customerLookup = Main.getConnection().prepareStatement(
                    "SELECT Customers.* " +
                    "FROM Customers " +
                    " WHERE Customers.ID=? ");
            customerLookup.setLong(1, customer);//-SaleType.CUSTOMER.code() * 10000l
            ResultSet rs = customerLookup.executeQuery();
            if (!rs.first()) {
                //no customer
                jCode.setText(" ");
                rs.close();
                return -1;
            } else {
                int creditLimit=rs.getInt("CreditLimit");
                rs.close();
                return creditLimit*100;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return -1;
    }
    int getDiscount(long customer){
        try{
            PreparedStatement customerLookup = Main.getConnection().prepareStatement(
                    "SELECT Customers.* " +
                    "FROM Customers " +
                    " WHERE Customers.ID=? ");
            customerLookup.setLong(1, customer);
            ResultSet rs = customerLookup.executeQuery();
            if (!rs.first()) {
                //no customer
                jCode.setText(" ");
                rs.close();
                return 0;
            } else {
                int localDiscount=rs.getInt("Discount");
                rs.close();
                return localDiscount;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return 0;
    }

    boolean getStop(long customer){
        try{
            PreparedStatement customerLookup = Main.getConnection().prepareStatement(
                    "SELECT Customers.Stop " +
                    "FROM Customers " +
                    " WHERE Customers.ID=? ");
            customerLookup.setLong(1, customer);//-SaleType.CUSTOMER.code() * 10000l
            ResultSet rs = customerLookup.executeQuery();
            if (!rs.first()) {
                //no custome
                rs.close();
                return true;
            } else {
                short stop=rs.getShort("Stop");
                rs.close();
                return stop==1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return true;
    }
}
