/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerDelivery.java
 *
 * Created on 29-Aug-2009, 10:21:41
 */

package proffittcenter;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Locale;
import java.util.prefs.Preferences;
import javax.swing.JRootPane;

/**
 *
 * @author HP_Owner
 */
public class CustomerDelivery extends EscapeDialog {

    int sale;
    Preferences root = Preferences.userNodeForPackage(getClass());
    private String name1;
    private String address1;
    private String address2;
    private String address3;
    private String postCode;
    private String county;
    private String town;
    private String customerOrder;
    private boolean saved=false;
    /** Creates new form CustomerDelivery */
    public CustomerDelivery(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JRootPane rp = getRootPane();
        rp.setDefaultButton(okButton);
    }

    public boolean execute(int sale) {
        this.sale = sale;
        customerOrderNumberText.setText("");
        jName.setText("");
        jAddress1.setText("");
        jTown.setText("");
        jCounty.setText("");
        jPostCode.setText("");
        customerOrderNumberText.requestFocus();
        setVisible(true);
//        //FormRestore.destroyPosition(this, root);
        return saved;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        customerOrderNumberText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jAddress1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTown = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCounty = new javax.swing.JTextField();
        jPostCode = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("proffittcenterworkingcopy/resource/CustomerDelivery"); // NOI18N
        setTitle(bundle.getString("CustomerDelivery.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("customerDelivery"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle.getString("CustomerDelivery.jLabel1.text")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setName("jLabel1"); // NOI18N

        customerOrderNumberText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customerOrderNumberText.setName("customerOrderNumberText"); // NOI18N
        customerOrderNumberText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerOrderNumberTextFocusLost(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText(bundle.getString("CustomerDelivery.jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jName.setName("jName"); // NOI18N
        jName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNameFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText(bundle.getString("CustomerDelivery.jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jAddress1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAddress1.setName("jAddress1"); // NOI18N
        jAddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAddress1FocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText(bundle.getString("CustomerDelivery.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jTown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTown.setName("jTown"); // NOI18N
        jTown.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTownFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText(bundle.getString("CustomerDelivery.jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jCounty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCounty.setName("jCounty"); // NOI18N
        jCounty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCountyFocusLost(evt);
            }
        });

        jPostCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPostCode.setName("jPostCode"); // NOI18N
        jPostCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPostCodeFocusLost(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenterworkingcopy/resource/OK.png"))); // NOI18N
        okButton.setBorderPainted(false);
        okButton.setContentAreaFilled(false);
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText(bundle.getString("CustomerDelivery.jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerOrderNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddress1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTown, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCounty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPostCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customerOrderNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            name1 = jName.getText();
            postCode=jPostCode.getText();
            address1 = jAddress1.getText();
            address2 = jName.getText();
            address3 = jName.getText();
            town=jTown.getText();
            county=jCounty.getText();
            customerOrder = customerOrderNumberText.getText();
            if((customerOrder+name1+postCode+address1+address2+address3+town+county+customerOrder).isEmpty()){
                saved=false;
                setVisible(false);
                return;
            }
            if(Main.settingsTab.authority==4){//trainee
                saved=true;
                setVisible(false);
                return;
            }
            PreparedStatement deliveryAddresses
                    = Main.getConnection().prepareStatement(
                    "INSERT INTO DeliveryAddresses " +
                    "(Sale,Name1,PostCode,Address1,Town,County,CustomerOrder) " +
                    "VALUES(?,?,?,?,?,?,?)");
            deliveryAddresses.setInt(1, sale);
            deliveryAddresses.setString(2, StringOps.firstCaps(name1));
            deliveryAddresses.setString(3,postCode.toUpperCase());
            deliveryAddresses.setString(4,StringOps.firstCaps(address1));
            deliveryAddresses.setString(5,StringOps.firstCaps(town));
            deliveryAddresses.setString(6,StringOps.firstCaps(county));
            deliveryAddresses.setString(7,customerOrder);
            deliveryAddresses.execute();
            saved=true;
            setVisible(false);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed

    private void customerOrderNumberTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerOrderNumberTextFocusLost
        customerOrderNumberText.setText(StringOps.firstCaps(customerOrderNumberText.getText()).trim());
    }//GEN-LAST:event_customerOrderNumberTextFocusLost

    private void jNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNameFocusLost
        jName.setText(StringOps.firstCaps(jName.getText()).trim());
    }//GEN-LAST:event_jNameFocusLost

    private void jAddress1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAddress1FocusLost
        jAddress1.setText(StringOps.firstCaps(jAddress1.getText()).trim());
    }//GEN-LAST:event_jAddress1FocusLost

    private void jTownFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTownFocusLost
        jTown.setText(StringOps.firstCaps(jTown.getText()).trim());
    }//GEN-LAST:event_jTownFocusLost

    private void jCountyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCountyFocusLost
        jCounty.setText(StringOps.firstCaps(jCounty.getText()).trim());
    }//GEN-LAST:event_jCountyFocusLost

    private void jPostCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPostCodeFocusLost
        jPostCode.setText(StringOps.firstCaps(jPostCode.getText()).trim());
    }//GEN-LAST:event_jPostCodeFocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerDelivery dialog = new CustomerDelivery(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerOrderNumberText;
    private javax.swing.JTextField jAddress1;
    private javax.swing.JTextField jCounty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jPostCode;
    private javax.swing.JTextField jTown;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
