/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LinkSkus.java
 *
 * Created on 22-Jun-2011, 17:34:03
 */
package proffittcenter;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dave
 */
public class LinkSkus extends EscapeDialog {

    private Integer firstSku;
    private Integer secondSku;
    private long firstBarcode;
    private long secondBarcode;
    private String up = "UPDATE Products SET Sku=? WHERE ID=?";
    private PreparedStatement ps;
    private String us = "UPDATE Skus SET Quantity = ? WHERE ID=?";
    private String gq = "SELECT Quantity FROM Skus WHERE ID=?";
    private int qty;
    private ResultSet rs;
    private Integer firstQty;
    private Integer secondQty;
    private Integer sum;

    /** Creates new form LinkSkus */
    public LinkSkus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        firstTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        secondTextField = new javax.swing.JTextField();
        linkToFirst = new javax.swing.JButton();
        linkToSecondButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        firstQuantityTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        secondQuantityTexField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sumTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        barcodeText1 = new javax.swing.JTextField();
        barcodeText2 = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("proffittcenter/resource/LinkSkus"); // NOI18N
        jTextField1.setText(bundle.getString("LinkSkus.jTextField1.text")); // NOI18N
        jTextField1.setName(bundle.getString("LinkSkus.jTextField1.name")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("null");
        setName("linkSkus"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle.getString("jLabel1")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        firstTextField.setName("firstTextField"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("jLabel2")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        secondTextField.setName("secondTextField"); // NOI18N

        linkToFirst.setText(bundle.getString("LinkSkus.linkToFirst.text")); // NOI18N
        linkToFirst.setName("linkToFirst"); // NOI18N
        linkToFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkToFirstActionPerformed(evt);
            }
        });

        linkToSecondButton.setText(bundle.getString("LinkSkus.linkToSecondButton.text")); // NOI18N
        linkToSecondButton.setName("linkToSecondButton"); // NOI18N
        linkToSecondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkToSecondButtonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle.getString("jLabel3")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        firstQuantityTextField.setText("null");
        firstQuantityTextField.setName("firstQuantityTextField"); // NOI18N
        firstQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstQuantityTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(bundle.getString("jLabel4")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        secondQuantityTexField.setText("null");
        secondQuantityTexField.setName("secondQuantityTexField"); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(bundle.getString("jLabel5")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        sumTextField.setText("null");
        sumTextField.setName("sumTextField"); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText(bundle.getString("LinkSkus.jLabel6.text")); // NOI18N
        jLabel6.setName(bundle.getString("LinkSkus.jLabel6.name")); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText(bundle.getString("LinkSkus.jLabel7.text")); // NOI18N
        jLabel7.setName(bundle.getString("LinkSkus.jLabel7.name")); // NOI18N

        barcodeText1.setText(bundle.getString("LinkSkus.barcodeText1.text")); // NOI18N
        barcodeText1.setName(bundle.getString("LinkSkus.barcodeText1.name")); // NOI18N
        barcodeText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeText1ActionPerformed(evt);
            }
        });

        barcodeText2.setText(bundle.getString("LinkSkus.barcodeText2.text")); // NOI18N
        barcodeText2.setName(bundle.getString("LinkSkus.barcodeText2.name")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linkToFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linkToSecondButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(barcodeText1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstTextField)
                                    .addComponent(firstQuantityTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(barcodeText2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(secondTextField)
                                    .addComponent(secondQuantityTexField))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(barcodeText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcodeText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(secondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(secondQuantityTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkToFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkToSecondButton))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {linkToFirst, linkToSecondButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkToFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkToFirstActionPerformed
        //link second product to first
        if (firstSku > 2 && secondSku>2) {//no linking to A or B
            try {                
                ps = Main.getConnection().prepareStatement(us);
                sum=Integer.parseInt(sumTextField.getText());
                ps.setInt(1, sum);
                ps.setInt(2, firstSku);
                ps.executeUpdate();
                ps = Main.getConnection().prepareStatement(up);
                ps.setInt(1, firstSku);
                ps.setLong(2, secondBarcode);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(LinkSkus.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Audio.play("Ring");
        }
        setVisible(false);
    }//GEN-LAST:event_linkToFirstActionPerformed

    private void linkToSecondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkToSecondButtonActionPerformed
        //link first product to second
        if (firstSku > 2 && secondSku > 2) {//no linking to A or B
            try {
                ps = Main.getConnection().prepareStatement(us);
                sum=Integer.parseInt(sumTextField.getText());
                ps.setInt(1, sum);
                ps.setInt(2, secondSku);
                ps.executeUpdate();
                ps = Main.getConnection().prepareStatement(up);
                ps.setInt(1, secondSku);
                ps.setLong(2, firstBarcode);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(LinkSkus.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Audio.play("Ring");
        }
        setVisible(false);
    }//GEN-LAST:event_linkToSecondButtonActionPerformed

    private void firstQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstQuantityTextFieldActionPerformed

    private void barcodeText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeText1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LinkSkus dialog = new LinkSkus(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcodeText1;
    private javax.swing.JTextField barcodeText2;
    private javax.swing.JTextField firstQuantityTextField;
    private javax.swing.JTextField firstTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton linkToFirst;
    private javax.swing.JButton linkToSecondButton;
    private javax.swing.JTextField secondQuantityTexField;
    private javax.swing.JTextField secondTextField;
    private javax.swing.JTextField sumTextField;
    // End of variables declaration//GEN-END:variables

    void execute(Integer firstSku, Integer secondSku, long firstBarcode, long secondBarcode) {
        try {
            if (firstSku < 0 || secondSku < 0 || firstSku == secondSku) {//not selected yet or the same
                Audio.play("Ring");
                return;
            }
            barcodeText1.setText(""+firstBarcode);
            barcodeText2.setText(""+secondBarcode);
            firstQuantityTextField.setText("");
            secondQuantityTexField.setText("");
            this.firstSku = firstSku;
            this.secondSku = secondSku;
            this.firstBarcode = firstBarcode;
            this.secondBarcode = secondBarcode;
            firstTextField.setText(firstSku.toString());
            secondTextField.setText(secondSku.toString());
            ps = Main.getConnection().prepareStatement(gq);
            ps.setInt(1, firstSku);
            rs = ps.executeQuery();
            if (rs.first()) {
                firstQty = rs.getInt("Quantity");
                firstQuantityTextField.setText(firstQty.toString());
            } else {
                rs.close();
                ps.close();
                return;
            }
            rs.close();
            ps = Main.getConnection().prepareStatement(gq);
            ps.setInt(1, secondSku);
            rs = ps.executeQuery();
            if (rs.first()) {
                secondQty = rs.getInt("Quantity");
                secondQuantityTexField.setText(secondQty.toString());
            } else {
                rs.close();
                ps.close();
                return;
            }
            rs.close();
            sum=firstQty+secondQty;
            sumTextField.setText(sum.toString());
            setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(LinkSkus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
