/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaidOut.java
 *
 * Created on 19-Sep-2008, 19:22:37
 */
package proffittcenter;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.ResourceBundle;
import java.util.prefs.Preferences;

/**
 *
 * @author HP_Owner
 */
public class PaidOut extends EscapeDialog {

     private static ResourceBundle bundle = ResourceBundle
            .getBundle("proffittcenter/resource/PaidOut");
    private Preferences root = Preferences.userNodeForPackage(getClass());
    private int amount;
    private boolean out;
    private ResultSet rs;
    private String amountString;
    private boolean noSale;

    /** Creates new form PaidOut */
    public PaidOut(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    void execute(boolean out,boolean noSale) {
        this.noSale=noSale;
        try {
            if(out&&!noSale){
                setTitle(java.util.ResourceBundle.getBundle("proffittcenter/resource/PaidOut").getString("PaidOut.title"));
            }else if(!noSale){
                setTitle(java.util.ResourceBundle.getBundle("proffittcenter/resource/PaidOut").getString("PaidIn"));
            } else {
                setTitle(java.util.ResourceBundle.getBundle("proffittcenter/resource/PaidOut").getString("noSale"));
            }
            this.out=out;
            jReason.removeAllItems();
            jReason.addItem("");
            PreparedStatement paidOutsQueryOut = Main.getConnection().prepareStatement(
                    "SELECT DISTINCT(UPPER(Description)) AS Description FROM PaidOuts " +
                    "WHERE Amount >0 ORDER BY  Description ");
            PreparedStatement paidOutsQueryIn = Main.getConnection().prepareStatement(
                    "SELECT DISTINCT(UPPER(Description)) AS Description FROM PaidOuts " +
                    "WHERE Amount <0 ORDER BY  Description ");
            PreparedStatement noSaleQuery = Main.getConnection().prepareStatement(
                    "SELECT DISTINCT(UPPER(Description)) AS Description FROM PaidOuts " +
                    "WHERE Amount =0 ORDER BY  Description ");
            if(out&&!noSale){
                rs = paidOutsQueryOut.executeQuery();
            }else if(!out && !noSale){
                rs = paidOutsQueryIn.executeQuery();
            }else {
                rs = noSaleQuery.executeQuery();
            }
            int i = 0;
            if (rs.first()) {
                //Description to display
                do {
                    //Description to display
                    String S = StringOps.firstCaps(rs.getString("Description").toLowerCase());
                    jReason.addItem(S.trim());
                } while (rs.next() && i < 7);
            }
            paidOutsQueryOut.close();
            paidOutsQueryIn.close();
        } catch (SQLException ex) {
            Audio.play("Ring");
        }
        amountTestField.setText("0");
        Audio.play("TaDa");
        jReason.setEditable(true);
        jReason.requestFocus();
        amountTestField.setFocusable(!noSale);
        amountTestField.setVisible(!noSale);
        jLabel2.setVisible(!noSale);
        getRootPane().setDefaultButton(okBtn);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jReason = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amountTestField = new javax.swing.JTextField();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("proffittcenter/resource/PaidOut"); // NOI18N
        setTitle(bundle.getString("PaidOut.title")); // NOI18N
        setName("PaidOut"); // NOI18N

        jReason.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Parking", "Item 2", "Item 3", "Item 4" }));
        jReason.setName("jReason"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenter/resource/OK.png"))); // NOI18N
        okBtn.setContentAreaFilled(false);
        okBtn.setName("okBtn"); // NOI18N
        okBtn.addActionListener(formListener);
        okBtn.addFocusListener(formListener);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenter/resource/Close24.png"))); // NOI18N
        closeButton.setContentAreaFilled(false);
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(formListener);
        closeButton.addKeyListener(formListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(okBtn, javax.swing.GroupLayout.Alignment.TRAILING, 0, 22, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle.getString("PaidOut.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("PaidOut.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        amountTestField.setName("amountTestField"); // NOI18N
        amountTestField.addKeyListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amountTestField)
                            .addComponent(jReason, 0, 151, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {amountTestField, jReason});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amountTestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener, java.awt.event.KeyListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == okBtn) {
                PaidOut.this.okBtnActionPerformed(evt);
            }
            else if (evt.getSource() == closeButton) {
                PaidOut.this.closeButtonActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == okBtn) {
                PaidOut.this.okBtnFocusGained(evt);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
        }

        public void keyPressed(java.awt.event.KeyEvent evt) {
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == closeButton) {
                PaidOut.this.closeButtonKeyReleased(evt);
            }
            else if (evt.getSource() == amountTestField) {
                PaidOut.this.amountTestFieldKeyReleased(evt);
            }
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        Audio.play("Beep");
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closeButtonKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            Audio.play("Beep");
            this.setVisible(false);
        }
    }//GEN-LAST:event_closeButtonKeyReleased

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        //Save the data or return to screen if faulty
        int n=0;
        String reason = (String) jReason.getSelectedItem();
        if (reason.isEmpty()) {
            Audio.play("Ring");
            jReason.requestFocus();
            return;
        }
        if(!noSale){
            amountString = StringOps.numericOnly(amountTestField.getText());
            n=Integer.parseInt(amountString);
            if (amountString.isEmpty()||n<=0) {
                Audio.play("Ring");
                amountTestField.requestFocus();
                amountTestField.selectAll();
                return;
            }
        }
        //now save
        try {
            PreparedStatement np = Main.getConnection().prepareStatement(
                    "INSERT INTO " +
                    " PaidOuts(ID,Description,Amount,TillID,Operator) " +
                    " VALUES(?,?,?,?,?)");
            np.setNull(1, Types.INTEGER);//ID
            String s=StringOps.firstCaps((String) jReason.getSelectedItem());
            np.setString(2, s.trim());//description
            if(out&&!noSale){
                np.setString(3, amountString);//price
            } else if(!noSale){
                np.setString(3, "-"+amountString);//price
            } else {
                np.setInt(3, 0);
            }
            np.setInt(4, Main.shop.getTillId());
            np.setInt(5, Main.operator.getOperator());
            np.executeUpdate();
            np.close();
            Main.receiptPrinter.cashDrawerOpen();
            //now print a receipt
            Main.receiptPrinter.startReceipt();
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            java.util.Date date = new java.util.Date();
            Main.receiptPrinter.printLine(Main.operator.operatorName);
            Main.receiptPrinter.printLine(bundle.getString("CurrentDateTime")+ " "+ dateFormat.format(date));
            Main.receiptPrinter.printLine(bundle.getString("TillNo")+ " "+Main.shop.getTillId());
            if(out&&!noSale){
                Main.receiptPrinter.printLine(bundle.getString("PaidOut"));
            } else if(!noSale){
                Main.receiptPrinter.printLine(bundle.getString("PaidIn"));
            } else {
                Main.receiptPrinter.printLine(bundle.getString("noSale"));
            }
            Main.receiptPrinter.printLine(s);//reason
            if(!noSale){
                Main.receiptPrinter.printLine(new Money(n).toString());
            }
            Main.receiptPrinter.endReceipt();
            Audio.play("Beep");
        } catch (SQLException ex) {
            Audio.play("Ring");
            System.out.println(bundle.getString("SQL_Error") + ex.getMessage());
        }
        setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed

    private void okBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_okBtnFocusGained
       if(!noSale){
            try {
                amount = Integer.parseInt(StringOps.numericOnly(amountTestField.getText()));
                amountTestField.setText((new Money(amount)).toString());
            } catch (NumberFormatException ex) {
                Audio.play("Ring");
                amountTestField.setText("");
                amountTestField.requestFocus();
                amountTestField.selectAll();
                return;
            }
       }
    }//GEN-LAST:event_okBtnFocusGained

    private void amountTestFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTestFieldKeyReleased
        Money.asMoney(amountTestField);
    }//GEN-LAST:event_amountTestFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PaidOut dialog = new PaidOut(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTestField;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jReason;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
}
