/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectMonthYear.java
 *
 * Created on 20-Feb-2010, 14:12:26
 */

package proffittcenter;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.prefs.Preferences;
import javax.swing.JRootPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 *
 * @author HP_Owner
 */
public class SelectMonthYear extends EscapeDialog {

    private Calendar theDate;
    private Preferences root = Preferences.userNodeForPackage(getClass());

    /** Creates new form SelectMonthYear
     * @param parent
     * @param modal  
     */
    public SelectMonthYear(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JRootPane rp = getRootPane();
        rp.setDefaultButton(okButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonth = new javax.swing.JSpinner();
        jYear = new javax.swing.JSpinner();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("proffittcenterworkingcopy/resource/SelectMonthYear"); // NOI18N
        setTitle(bundle.getString("title")); // NOI18N
        setName("SelectMonthYear"); // NOI18N

        jMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jMonth.setName("jMonth"); // NOI18N

        jYear.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, null, 1));
        jYear.setName("jYear"); // NOI18N

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenterworkingcopy/resource/OK.png"))); // NOI18N
        okButton.setContentAreaFilled(false);
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("SelectMonthYear.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(bundle.getString("SelectMonthYear.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jMonth, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jYear, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // set month/year to theDate
        int month = (Integer)jMonth.getValue();
        int year = (Integer)jYear.getValue();
//        theDate.set((Integer)jYear.getValue(), (Integer)jMonth.getValue(), 1);
        theDate=Calendar.getInstance();
        theDate.set(Calendar.YEAR,year);
        theDate.set(Calendar.MONTH,month);
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    public Calendar execute(){
        theDate=Calendar.getInstance();
        int year = theDate.get(Calendar.YEAR);
        int month = theDate.get(Calendar.MONTH)+1;
//        theDate.set(0, 0, 1);
        jMonth.setValue(month);
        jYear.setValue(year);
        jMonth.requestFocus();
        final JTextField tf = ((JSpinner.DefaultEditor) jMonth.getEditor()).getTextField();
        ActionListener al = new ActionListener()  {
            public void actionPerformed(ActionEvent ae) {
                tf.requestFocusInWindow();
                tf.selectAll();     
            }
        };
        int delay = 100;//modify to suit  
        javax.swing.Timer timer = new javax.swing.Timer(delay, al);
        timer.setRepeats(false);
        timer.start();
        theDate=null;
        setVisible(true);
        return theDate;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectMonthYear dialog = new SelectMonthYear(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jMonth;
    private javax.swing.JSpinner jYear;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
