/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Shop.java
 *
 * Created on 21-Sep-2010, 11:54:12
 */

package proffittcenter;

import java.nio.charset.Charset;
import java.text.NumberFormat;
import java.util.Currency;
import java.util.Iterator;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;

/**
 *
 * @author Dave
 */
public class Shop_2 extends javax.swing.JPanel {
    
    Preferences root = Preferences.userNodeForPackage(getClass());
//    static Preferences systemRoot = Preferences.systemNodeForPackage(Shop.class);
    static ResourceBundle bundle = ResourceBundle.getBundle("proffittcenterworkingcopy/resource/Settings");
    static ResourceBundle regimeBundle = ResourceBundle.getBundle("proffittcenterworkingcopy/resource/Regime");
    Currency currency = Currency.getInstance(Locale.getDefault());
    public String poundSymbol = java.util.Currency.getInstance(Locale.getDefault()).getSymbol();//root.get("PoundSymbol", "�");
    private String pennySymbol = root.get("PennySymbol", "p");
    private String kgSymbol = root.get("kgSymbol", "kg");
    private Integer tillId = Integer.parseInt(root.get("TillId", "1"));
    public Integer minimumDebit = Integer.parseInt(root.get("MinimumDebit", "500"));
    public String tax = root.get("Tax", "Registered");
    public String companyName = root.get("CompanyName", "");
    public String companyAddress = root.get("CompanyAddress", "9 Invicta Road");
    public String companyPhone = root.get("CompanyPhone", "01795 581467");
    public String companyTaxID = root.get("CompanyTaxID", "01234567");
    public String charset = root.get("Charset", "Cp850");
    public Boolean receiptAlways = Boolean.parseBoolean(root.get("ReceiptAlways", "false"));
    public boolean videoRental = Boolean.parseBoolean(root.get("VideoRental", "false"));
    private boolean jasperInMyDocuments = true;
    String regime;
    private boolean cashBack = root.getBoolean("CashBack", true);
    private int printReceiptOnGreaterThan = root.getInt("ReceiptOnGreaterThan", 0);
    public int fixedFloat = 0;
    private int shiftFloat = fixedFloat;//in pence
    public final String myCountry="";
    public static int floatID = 0;
    private int minimumValue;
    private Regime regimeIs;
    private int taxId=root.getInt("Tax", 1);
    private int autoclearMinutes = root.getInt("autoclearMinutes", 3);
    private boolean speech =root.getBoolean("speech", false);
    private Integer rounding = Integer.parseInt(root.get("rounding", "1"));
    private boolean newProduct = root.getBoolean("newProduct", true);
    public boolean closeComputer = root.getBoolean("closeComputer", true);
    private int cashDrawerLimit = root.getInt("cashDrawerLimit", 0);
    
    /** Creates new form Shop */
    public Shop_2() {
        initComponents();
        poundSymbol =  root.get("PoundSymbol", poundSymbol);
        regimeIs = (tax.compareToIgnoreCase(regimeBundle.getString("Registered")) == 0) ?
            Regime.REGISTERED : (tax.compareToIgnoreCase(regimeBundle.getString("SalesTax")) == 0) ?
                Regime.SALESTAX : (tax.compareToIgnoreCase(regimeBundle.getString("Unregistered")) == 0) ?
                    Regime.UNREGISTERED : (tax.compareToIgnoreCase(regimeBundle.getString("Wholesale")) == 0) ?
                        Regime.WHOLESALE
                        : Regime.NONE;
        cashDrawerLimitSpinner.setValue(cashDrawerLimit);
        companyName=root.get("CompanyName", "");
        companyAddress=root.get("CompanyAddress", "");
        companyPhone = root.get("CompanyPhone", "");
        companyTaxID = root.get("CompanyTaxID", "01234567");
        charset = root.get("Charset", "Cp850");
        receiptAlways = Boolean.parseBoolean(root.get("ReceiptAlways", "false"));
        videoRental = Boolean.parseBoolean(root.get("VideoRental", "false"));
        jasperInMyDocuments = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLocale = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        charsetCombo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jPoundSymbol = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPennySymbol = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jMinimumDebit = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jCharSet = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jReceiptAlways = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        receiptSpinner = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jCashBack = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        floatSpinner = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jRegime = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jasperCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTaxId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTillId = new javax.swing.JSpinner();
        autoClearSpinner = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        kgSymbolText = new javax.swing.JTextField();
        speechCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        roundingSpinner = new javax.swing.JSpinner();
        newProductCheckBox = new javax.swing.JCheckBox();
        closeComputerCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cashDrawerLimitSpinner = new javax.swing.JSpinner();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("proffittcenterworkingcopy/resource/Settings"); // NOI18N
        setName(bundle.getString("Shop.name")); // NOI18N

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("proffittcenterworkingcopy/resource/CashupReconciliation"); // NOI18N
        jLabel19.setText(bundle1.getString("Settings.jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLocale.setText(bundle1.getString("Settings.jLocale.text")); // NOI18N
        jLocale.setName("jLocale"); // NOI18N

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText(bundle1.getString("Settings.jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        charsetCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        charsetCombo.setName("charsetCombo"); // NOI18N

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText(bundle1.getString("Settings.jLabel15.text_1")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jPoundSymbol.setName("jPoundSymbol"); // NOI18N

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText(bundle1.getString("Settings.jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jPennySymbol.setName("jPennySymbol"); // NOI18N

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText(bundle1.getString("Settings.jLabel17.text_1")+" ("+pennySymbol+"):"); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jMinimumDebit.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jMinimumDebit.setName("jMinimumDebit"); // NOI18N

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText(bundle1.getString("Settings.jLabel18.text_1")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jCharSet.setFocusable(false);
        jCharSet.setName("jCharSet"); // NOI18N

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText(bundle1.getString("Settings.jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jReceiptAlways.setName("jReceiptAlways"); // NOI18N

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText(bundle1.getString("Settings.jLabel23.text")+" ("+pennySymbol+"):"); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        receiptSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        receiptSpinner.setName("receiptSpinner"); // NOI18N

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText(bundle1.getString("Settings.jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        jCashBack.setSelected(true);
        jCashBack.setName("jCashBack"); // NOI18N

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText(bundle1.getString("Settings.jLabel27.text")+" ("+pennySymbol+"):"); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        floatSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        floatSpinner.setName("floatSpinner"); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText(bundle1.getString("Settings.jLabel11.text_1")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jRegime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jRegime.setName("jRegime"); // NOI18N

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText(bundle1.getString("Settings.jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N

        jasperCheckBox.setText(bundle.getString("NormallyChecked")); // NOI18N
        jasperCheckBox.setName("jasperCheckBox"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle1.getString("Settings.jLabel1.text_1")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setName("jLabel1"); // NOI18N

        jCompanyName.setName("jCompanyName"); // NOI18N
        jCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompanyNameActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle1.getString("Settings.jLabel2.text_1")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setName("jLabel2"); // NOI18N

        jAddress.setName("jAddress"); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle1.getString("Settings.jLabel3.text_1")); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setName("jLabel3"); // NOI18N

        jPhone.setName("jPhone"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(bundle1.getString("Settings.jLabel4.text_1")); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setName("jLabel4"); // NOI18N

        jTaxId.setName("jTaxId"); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText(bundle1.getString("Settings.jLabel10.text_1")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jTillId.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        jTillId.setName("jTillId"); // NOI18N

        autoClearSpinner.setModel(new javax.swing.SpinnerNumberModel(0, -1, null, 1));
        autoClearSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(autoClearSpinner, ""));
        autoClearSpinner.setName("autoClearSpinner"); // NOI18N

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText(bundle.getString("Shop.jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText(bundle.getString("Shop.jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        kgSymbolText.setName("kgSymbolText"); // NOI18N

        speechCheckBox.setText(bundle.getString("Shop.speechCheckBox.text")); // NOI18N
        speechCheckBox.setName("speechCheckBox"); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(bundle.getString("Shop.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        roundingSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"1", "2", "5", "10", "20"}));
        roundingSpinner.setName("roundingSpinner"); // NOI18N

        newProductCheckBox.setText(bundle.getString("shop.New")); // NOI18N
        newProductCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        newProductCheckBox.setName("newProductCheckBox"); // NOI18N

        closeComputerCheckBox.setText(bundle.getString("Shop.closeComputerCheckBox.text")); // NOI18N
        closeComputerCheckBox.setName("closeComputerCheckBox"); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText(bundle.getString("Shop.jLabel6.text_1")+" ("+pennySymbol+"):"); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        cashDrawerLimitSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100000, 1));
        cashDrawerLimitSpinner.setName("cashDrawerLimitSpinner"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLocale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(charsetCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPoundSymbol)
                            .addComponent(jPennySymbol)
                            .addComponent(jMinimumDebit)
                            .addComponent(jCharSet)
                            .addComponent(jReceiptAlways, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receiptSpinner)
                            .addComponent(jCashBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(floatSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(newProductCheckBox)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(autoClearSpinner)
                                .addGap(16, 16, 16)))))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeComputerCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundingSpinner)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRegime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCompanyName)
                            .addComponent(jAddress)
                            .addComponent(jPhone)
                            .addComponent(jTaxId)
                            .addComponent(jTillId)
                            .addComponent(kgSymbolText)
                            .addComponent(speechCheckBox)
                            .addComponent(jasperCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashDrawerLimitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel22, jLabel23, jLabel25, jLabel26, jLabel27});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {charsetCombo, floatSpinner, jCashBack, jCharSet, jLocale, jMinimumDebit, jPennySymbol, jPoundSymbol, jReceiptAlways, receiptSpinner});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAddress, jCompanyName, jPhone, jRegime, jTaxId, jTillId, jasperCheckBox, kgSymbolText});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel2, jLabel21, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLocale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33)
                    .addComponent(jasperCheckBox))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRegime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTaxId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTillId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kgSymbolText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(speechCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(charsetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPoundSymbol)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPennySymbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMinimumDebit)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCharSet)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel25)
                            .addComponent(jReceiptAlways))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(receiptSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel26)
                            .addComponent(jCashBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autoClearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel5)
                            .addComponent(roundingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cashDrawerLimitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeComputerCheckBox)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newProductCheckBox)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jAddress, jCompanyName, jLabel33, jPhone, jRegime, jTaxId, jTillId, jasperCheckBox});

    }// </editor-fold>//GEN-END:initComponents

    private void jCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompanyNameActionPerformed
        
}//GEN-LAST:event_jCompanyNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner autoClearSpinner;
    private javax.swing.JSpinner cashDrawerLimitSpinner;
    private javax.swing.JComboBox charsetCombo;
    private javax.swing.JCheckBox closeComputerCheckBox;
    private javax.swing.JSpinner floatSpinner;
    private javax.swing.JTextField jAddress;
    private javax.swing.JCheckBox jCashBack;
    private javax.swing.JTextField jCharSet;
    private javax.swing.JTextField jCompanyName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLocale;
    private javax.swing.JSpinner jMinimumDebit;
    private javax.swing.JTextField jPennySymbol;
    private javax.swing.JTextField jPhone;
    private javax.swing.JTextField jPoundSymbol;
    private javax.swing.JCheckBox jReceiptAlways;
    private javax.swing.JComboBox jRegime;
    private javax.swing.JTextField jTaxId;
    private javax.swing.JSpinner jTillId;
    private javax.swing.JCheckBox jasperCheckBox;
    private javax.swing.JTextField kgSymbolText;
    private javax.swing.JCheckBox newProductCheckBox;
    private javax.swing.JSpinner receiptSpinner;
    private javax.swing.JSpinner roundingSpinner;
    private javax.swing.JCheckBox speechCheckBox;
    // End of variables declaration//GEN-END:variables

    void execute() {
        jasperInMyDocuments = root.getBoolean("JasperInMyDocuments", true);
        jasperCheckBox.setSelected(jasperInMyDocuments);
//        regime = Regime.description(tax).toString();
        jCompanyName.setText(root.get("CompanyName", ""));
        jAddress.setText(root.get("CompanyAddress", "100 AnyStreet"));
        jPhone.setText(root.get("CompanyPhone", "01795 581467"));
        jTaxId.setText(root.get("CompanyTaxID", "01234567"));
        String s = StringOps.numericOnly(root.get("TillId", "1"));
        tillId = Integer.parseInt(s);
        jTillId.setValue(tillId);
        jRegime.removeAllItems();
        for (int i = 0; i < Regime.count(); i++) {
            jRegime.addItem(Regime.typeOf(i).toString());
        }
        jRegime.setSelectedItem((Object) root.get("Tax", "Registered"));
        NumberFormat nf = NumberFormat.getCurrencyInstance();
        pennySymbol = "c";
        jPoundSymbol.setText(poundSymbol);
        if (poundSymbol.equalsIgnoreCase("£")) {
            pennySymbol = "p";
            kgSymbol="kg";
        }
        if (poundSymbol.equalsIgnoreCase("$")) {
            pennySymbol = "c";
            kgSymbol="lb";
        }
        if (poundSymbol.equalsIgnoreCase("€")) {
            pennySymbol = "c";
            kgSymbol="kg";
        }
        jPennySymbol.setText(root.get("PennySymbol", pennySymbol));
        kgSymbolText.setText(root.get("kgSymbol", getKgSymbol()));
        s = root.get("MinimumDebit", "500");
        minimumDebit = Integer.parseInt(s);
        jMinimumDebit.setValue(minimumDebit);
        charset = root.get("Charset", "Cp850");
        jCharSet.setText(charset);
        receiptAlways = root.getBoolean("ReceiptAlways", false);
        jReceiptAlways.setSelected(receiptAlways);
        printReceiptOnGreaterThan = root.getInt("ReceiptOnGreaterThan", 0);
        cashBack = root.getBoolean("CashBack", true);
        jCashBack.setSelected(cashBack);
        jasperInMyDocuments = root.getBoolean("JasperInMyDocuments", true);
        jasperCheckBox.setSelected(isJasperInMyDocuments());
        
        charsetCombo.removeAllItems();
        charsetCombo.addItem("");
        charsetCombo.addItem("Cp850");//needed here
        Map map = Charset.availableCharsets();
        Iterator it = map.keySet().iterator();
        while (it.hasNext()) {
            String charsetName = (String) it.next();
            charsetCombo.addItem(charsetName);
            int x = 0;
        }
        charsetCombo.setSelectedItem(charset);
        autoclearMinutes = root.getInt("autoclearMinutes", 3);
        autoClearSpinner.setValue(getAutoclearMinutes());
//        charset = root.get("Charset", "");//default should be blank
        speech = root.getBoolean("speech", false);
        speechCheckBox.setSelected(isSpeech());
        newProduct=root.getBoolean("newProduct", true);
        newProductCheckBox.setSelected(isNewProduct());
        rounding = Integer.parseInt(root.get("rounding", "1"));
        roundingSpinner.setValue(""+getRounding());
        closeComputerCheckBox.setSelected(closeComputer);
    }
    
    /**
     * @return the tillId
     */
    public Integer getTillId() {
        return tillId;
    }
    
    /**
     * @return the shiftFloat
     */
    public int getShiftFloat() {
        shiftFloat = root.getInt("ShiftFloat", this.shiftFloat);
        return shiftFloat;
    }

    /**
     * @param shiftFloat the shiftFloat to set
     */
    public void setShiftFloat(int shiftFloat) {
        this.shiftFloat = shiftFloat;
        root.putInt("ShiftFloat", this.shiftFloat);
    }

    
    /**
     * @return the jasperInMyDocuments
     */
    public boolean isJasperInMyDocuments() {
        return jasperInMyDocuments;
    }

 /**
     * @return the cashBack
     */
    public boolean isCashBack() {
        return cashBack;
    }

    int getReceiptSpinnerValue() {
        return printReceiptOnGreaterThan;
    }
    
    public boolean isVideoRental() {
        return videoRental;
    }
    
    
    public boolean ok(){
        poundSymbol = jPoundSymbol.getText();
        root.put("PoundSymbol", poundSymbol);
        pennySymbol = jPennySymbol.getText();
        root.put("PennySymbol", pennySymbol);
        kgSymbol = kgSymbolText.getText();
        root.put("kgSymbol", getKgSymbol());
        tillId = (Integer) jTillId.getValue();
        root.putInt("TillId", getTillId());
        minimumDebit = (Integer) jMinimumDebit.getValue();
        root.putInt("MinimumDebit", minimumDebit);
        taxId= jRegime.getSelectedIndex();
//        tax = (String) jRegime.getSelectedIndex().toString();
        String s=Regime.typeOf(taxId).toString();
        root.put("Tax", s);
        companyName = jCompanyName.getText();
        root.put("CompanyName", companyName);
        companyAddress = jAddress.getText();
        root.put("CompanyAddress", companyAddress);
        companyPhone = jPhone.getText();
        root.put("CompanyPhone", companyPhone);
        companyTaxID = jTaxId.getText();
        root.put("CompanyTaxID", companyTaxID);
        receiptAlways = jReceiptAlways.isSelected();
        root.putBoolean("ReceiptAlways", receiptAlways);
        printReceiptOnGreaterThan = (Integer) receiptSpinner.getValue();
        root.putInt("ReceiptOnGreaterThan", printReceiptOnGreaterThan);
        fixedFloat = (Integer) floatSpinner.getValue();
        root.putInt("Float", fixedFloat);
        jasperInMyDocuments = jasperCheckBox.isSelected();
        root.putBoolean("JasperInMyDocuments", isJasperInMyDocuments());
        cashBack = jCashBack.isSelected();
        root.putBoolean("CashBack", cashBack);
        charset = jCharSet.getText();
        root.put("CharSet", charset);
        autoclearMinutes=(Integer) autoClearSpinner.getValue();
        root.putInt("autoclearMinutes", getAutoclearMinutes());
        speech = speechCheckBox.isSelected();
        root.putBoolean("speech", isSpeech());
        newProduct = newProductCheckBox.isSelected();
        root.putBoolean("newProduct", isNewProduct());
        rounding = Integer.parseInt((String)roundingSpinner.getValue());
        root.put("rounding", ""+getRounding());
        cashDrawerLimit=(Integer)cashDrawerLimitSpinner.getValue();
        root.putInt("cashDrawerLimit", getCashDrawerLimit());
        closeComputer = closeComputerCheckBox.isSelected();
        root.putBoolean("closeComputer", closeComputer);
        
        return true;
    }
    
    public Regime regimeIs() {
        return regimeIs;
    }
    
    /**
     * @return the pennySymbol
     */
    public String getPennySymbol() {
        return pennySymbol;
    }

    /**
     * @return the autoclearSeconds
     */
    public int getAutoclearMinutes() {
        return autoclearMinutes;
    }

    /**
     * @return the kgSymbol
     */
    public String getKgSymbol() {
        return kgSymbol;
    }

    /**
     * @return the speech
     */
    public boolean isSpeech() {
        return speech;
    }

    /**
     * @return the rounding
     */
    public Integer getRounding() {
        return rounding;
    }

    /**
     * @return the newProduct
     */
    public boolean isNewProduct() {
        return newProduct;
    }

    /**
     * @return the cashDrawerLimit
     */
    public int getCashDrawerLimit() {
        return cashDrawerLimit;
    }
    
}
