/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SupplierN.java
 *
 * Created on 19-Mar-2009, 05:37:03
 */
package proffittcenter;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.prefs.Preferences;
import javax.swing.JRootPane;

/**
 *
 * @author HP_Owner
 */
public class Supplier extends EscapeDialog {

    Preferences root = Preferences.userNodeForPackage(getClass());

    /** Creates new form SupplierN */
    public Supplier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Main.mainHelpBroker.enableHelpKey(getRootPane(), "Supplier", Main.mainHelpSet);
        JRootPane rp = getRootPane();
        rp.setDefaultButton(okBtn);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jPostCode = new javax.swing.JTextField();
        jPhoneNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        closeButton2 = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jWeeksCredit = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jDays = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("proffittcenter/resource/Supplier"); // NOI18N
        setTitle(bundle.getString("Supplier.title")); // NOI18N
        setName("Supplier"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle.getString("Supplier.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jId.setEditable(false);
        jId.setFocusable(false);
        jId.setName("jId"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("Supplier.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jDescription.setName("jDescription"); // NOI18N
        jDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDescriptionFocusLost(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle.getString("Supplier.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(bundle.getString("Supplier.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jAddress.setName("jAddress"); // NOI18N
        jAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAddressFocusLost(evt);
            }
        });

        jPostCode.setName("jPostCode"); // NOI18N
        jPostCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPostCodeFocusLost(evt);
            }
        });

        jPhoneNumber.setName("jPhoneNumber"); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText(bundle.getString("Supplier.jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jCheckBox1.setText(bundle.getString("Supplier.jCheckBox1.text")); // NOI18N
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jCheckBox2.setText(bundle.getString("Supplier.jCheckBox2.text")); // NOI18N
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        jCheckBox3.setText(bundle.getString("Supplier.jCheckBox3.text")); // NOI18N
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox3.setName("jCheckBox3"); // NOI18N

        jCheckBox4.setText(bundle.getString("Supplier.jCheckBox4.text")); // NOI18N
        jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox4.setName("jCheckBox4"); // NOI18N

        jCheckBox5.setText(bundle.getString("Supplier.jCheckBox5.text")); // NOI18N
        jCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox5.setName("jCheckBox5"); // NOI18N

        jCheckBox6.setText(bundle.getString("Supplier.jCheckBox6.text")); // NOI18N
        jCheckBox6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox6.setName("jCheckBox6"); // NOI18N

        jCheckBox7.setText(bundle.getString("Supplier.jCheckBox7.text")); // NOI18N
        jCheckBox7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox7.setName("jCheckBox7"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        closeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenter/resource/Close24.png"))); // NOI18N
        closeButton2.setBorderPainted(false);
        closeButton2.setContentAreaFilled(false);
        closeButton2.setName("closeButton2"); // NOI18N
        closeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton2ActionPerformed(evt);
            }
        });

        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proffittcenter/resource/OK.png"))); // NOI18N
        okBtn.setContentAreaFilled(false);
        okBtn.setName("okBtn"); // NOI18N
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(724, Short.MAX_VALUE)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(okBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(bundle.getString("Supplier.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText(bundle.getString("Supplier.jLabe6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jWeeksCredit.setModel(new javax.swing.SpinnerNumberModel(0, 0, 52, 1));
        jWeeksCredit.setName("jWeeksCredit"); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(bundle.getString("Supplier.jLabel7.text")); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setName("jLabel7"); // NOI18N

        jDays.setModel(new javax.swing.SpinnerNumberModel(0, 0, 365, 7));
        jDays.setName("jDays"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jWeeksCredit)
                                        .addGap(321, 321, 321)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDays, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPhoneNumber)
                                    .addComponent(jPostCode)
                                    .addComponent(jAddress)
                                    .addComponent(jDescription)
                                    .addComponent(jId, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7)
                                .addGap(121, 121, 121))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWeeksCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton2ActionPerformed
        Audio.play("Beep");
        setVisible(false);
}//GEN-LAST:event_closeButton2ActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        description = StringOps.firstCaps(jDescription.getText());
        phoneNumber = jPhoneNumber.getText();
        if (jDescription.getText().isEmpty()) {
            //set focus back to descriptionTextField
            jDescription.requestFocus();
            Audio.play("Ring");
            return;
        } else if (jPhoneNumber.getText().isEmpty()) {
            //set focus back to jTax
            jPhoneNumber.requestFocus();
            Audio.play("Ring");
            return;
        } else if (jPostCode.getText().length()>10){
            jPostCode.requestFocus();
            Audio.play("Ring");
            return;
        }
        //need to save all reults
        if(!saveData()){
            return;
        }
        setVisible(false);
}//GEN-LAST:event_okBtnActionPerformed

    private void jDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDescriptionFocusLost
       description = StringOps.firstCaps(jDescription.getText());
            jDescription.setText(description);
    }//GEN-LAST:event_jDescriptionFocusLost

    private void jAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAddressFocusLost
        address = StringOps.firstCaps(jAddress.getText());
            jAddress.setText(address);
    }//GEN-LAST:event_jAddressFocusLost

    private void jPostCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPostCodeFocusLost
        postCode=jPostCode.getText().toUpperCase();
        jPostCode.setText(postCode);
    }//GEN-LAST:event_jPostCodeFocusLost

    public void execute(String ids) {
        //show the details
        this.ids = ids;
        if (ids.isEmpty()) {//create a new record
            updating = false;
            deliveryDays=0;
            jId.setText("");
            jDescription.setText("");
            jAddress.setText("");
            jPostCode.setText("");
            jPhoneNumber.setText("");
            deliveryDays = 0;
            weeksCredit = 0;
            jWeeksCredit.setValue(weeksCredit);
            daysToNextDelivery = 0;
            jDays.setValue(daysToNextDelivery);
        } else {//lookup old record
            updating = true;
            try {
                PreparedStatement lu;
                lu = Main.getConnection().prepareStatement(
                        "SELECT Suppliers.*,DeliveryDays+0 AS DD " +
                        "FROM Suppliers " +
                        "WHERE Suppliers.ID=? AND ID>1 " +
                        "ORDER BY Description");
                lu.setString(1, ids);
                ResultSet rs = lu.executeQuery();
                if (rs.last()) {
                    jId.setText(ids);
                    jDescription.setText(rs.getString("Description"));
                    jAddress.setText(rs.getString("Address"));
                    jPostCode.setText(rs.getString("PostCode"));
                    jPhoneNumber.setText(rs.getString("PhoneNumber"));
                    deliveryDays = rs.getInt("DD");
                    weeksCredit = rs.getInt("WeeksCredit");
                    jWeeksCredit.setValue(weeksCredit);
                    daysToNextDelivery = rs.getInt("DaysToNextDelivery");
                    jDays.setValue(daysToNextDelivery);
                } else {//no supplier
                    Audio.play("Ring");
                    return;
                }
                rs.close();
            } catch (SQLException ex) {
                Audio.play("Ring");
                ex.printStackTrace();
            }
            jCheckBox1.setSelected((deliveryDays & 1) != 0);//Monday
            jCheckBox2.setSelected((deliveryDays & 2) != 0);//Tuesday
            jCheckBox3.setSelected((deliveryDays & 4) != 0);//Wednesday
            jCheckBox4.setSelected((deliveryDays & 8) != 0);//Thursday
            jCheckBox5.setSelected((deliveryDays & 16) != 0);//Friday
            jCheckBox6.setSelected((deliveryDays & 32) != 0);//Saturday
            jCheckBox7.setSelected((deliveryDays & 64) != 0);//Sunday
        }
        Audio.play("Tada");
        jDescription.requestFocus();
        jDescription.selectAll();
        //FormRestore.createPosition(this, root);
        setVisible(true);
        //FormRestore.destroyPosition(this, root);
        return;
    }

    private boolean saveData() {
        dys=0;
       if (jCheckBox1.isSelected()) {//Monday
            dys += 1;
        }
        if (jCheckBox2.isSelected()) {//Tuesday
            dys += 2;
        }
        if (jCheckBox3.isSelected()) {//Wednesday
            dys += 4;
        }
        if (jCheckBox4.isSelected()) {//Thursday
            dys += 8;
        }
        if (jCheckBox5.isSelected()) {//Friday
            dys += 16;
        }
        if (jCheckBox6.isSelected()) {//Saturday
            dys += 32;
        }
        if (jCheckBox7.isSelected()) {//Sunday
            dys += 64;
        }
        description = StringOps.firstCaps(jDescription.getText());
        address = StringOps.firstCaps(jAddress.getText());
        postCode = jPostCode.getText().toUpperCase();
        phoneNumber = jPhoneNumber.getText().toUpperCase();
        weeksCredit = (Integer) jWeeksCredit.getModel().getValue();
        daysToNextDelivery = (Integer) jDays.getModel().getValue();
        try {
            if (updating) {
                PreparedStatement pu = Main.getConnection().prepareStatement(
                        "UPDATE Suppliers SET " +
                        "description=?," +
                        "Address=?," +
                        "PostCode=?," +
                        "PhoneNumber=?, " +
                        "DeliveryDays=?, " +
                        "WeeksCredit=?, " +
                        "DaysToNextDelivery=? " +
                        "WHERE ID=? AND id!=1");
                pu.setString(1, description);
                pu.setString(2, StringOps.fixLength(address.trim(), 60));
                pu.setString(3, StringOps.fixLength(postCode.trim(), 10));
                pu.setString(4, StringOps.fixLength(phoneNumber.trim(), 10));
                pu.setInt(5, dys);
                pu.setInt(6, (Integer) jWeeksCredit.getModel().getValue());
                pu.setInt(7, (Integer) jDays.getModel().getValue());
                pu.setString(8, ids);
                pu.executeUpdate();
            } else {//new supplier
                //check if description already in database
                PreparedStatement stopDuplicates=Main.getConnection().prepareStatement("SELECT * FROM Suppliers WHERE Description=?");
                stopDuplicates.setString(1, description);
                ResultSet rs=stopDuplicates.executeQuery();
                if(rs.first()){
                    //we have a duplicate
                    jDescription.setText("");
                    jDescription.requestFocus();
                    Audio.play("Ring");
                    return false;
                }
                PreparedStatement pn = Main.getConnection().prepareStatement(
                        "INSERT INTO " +
                        "Suppliers " +
                        "(id,description,address,PostCode,phoneNumber,DeliveryDays,WeeksCredit,DaysToNextDelivery) " +
                        "VALUES(?,?,?,?,?,?,?,?)");
                pn.setNull(1, Types.INTEGER);
                pn.setString(2, description);
                pn.setString(3, address);
                pn.setString(4, postCode);
                pn.setString(5, phoneNumber);
                pn.setInt(6, dys);
                pn.setInt(7, weeksCredit);
                pn.setInt(8, daysToNextDelivery);
                pn.executeUpdate();
            }
        } catch (SQLException ex) {
            Audio.play("Ring");
            ex.printStackTrace();
            return false;
        }
        Audio.play("Beep");
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Supplier dialog = new Supplier(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton2;
    private javax.swing.JTextField jAddress;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JSpinner jDays;
    private javax.swing.JTextField jDescription;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPhoneNumber;
    private javax.swing.JTextField jPostCode;
    private javax.swing.JSpinner jWeeksCredit;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
    private String ids;
    private boolean updating = false;
    private String phoneNumber;
    private String description;
    private int deliveryDays = 0;
    private int weeksCredit;
    private int daysToNextDelivery;
    private String address;
    private String postCode;
    private int dys = 0;
}
